---
title: "Opening Act"
author: "BK"
date: "2025-08-03"
categories: [performance]
---

The Activities Committee ask me to perform.

To open the Ward Dance Party.

By this time, my, instinctive, automatic reply was YES, of course.

Then the struggle began.

What to do for the opening act.

Ran my selection by a member, a former DJ himself.

Bishop K, it doesn't matter what the number is, they like you.

Therefore they will like the number.

Finally, settled on 붏은노을

Struggled and rehearsed for a better part of a month

## Big Bang Cover

<https://www.youtube.com/watch?v=QhjgPFu9K28&list=RDQhjgPFu9K28&start_radio=1>

<https://www.youtube.com/watch?v=oJIWY9W5WAM&list=RDoJIWY9W5WAM&start_radio=1>

## The Original by 이문세

<https://www.youtube.com/watch?v=NfuELl2KZHM&list=RDNfuELl2KZHM&start_radio=1>

## The performed version

<https://www.youtube.com/watch?v=laTwNsKrGrE&list=RDlaTwNsKrGrE&start_radio=1>

My performance to open the Dance fell far short of expectations, both Ward Members and myself.

But I didn't mind.

At my age, just being asked to perform was enough.

Then choosing a song from the 1980s, remade in 2008, performed by the original singer in a award ceremony in 2019

Lastly akwardly performed by a Bishop of a YSA Ward.

The song had a uniting effect, spanning nearly 4 decades of audiences

## Lyric Parity

> 난 너를 사랑해 이 세상은 너 뿐이야 소리쳐 부르지만 저 대답 없는 노을만 붉게 타는데
